experimental:
  localPlugins:
    crlchecker:
      modulename: "github.com/GLMONTER/crlchecker"

entryPoints:
  web:
    address: ":80"

api:
  dashboard: true

providers:
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true
