#uncomment to test locally

#experimental:
#  localPlugins:
#    crlchecker:
#      modulename: "github.com/GLMONTER/crlchecker"

#comment to test locally
experimental:
  plugins:
    crlchecker:
      modulename: "github.com/GLMONTER/crlchecker"
      version: "v1.0.1"

entryPoints:
  web:
    address: ":80"

api:
  dashboard: true

providers:
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true
